import './bootstrap';
import '@fortawesome/fontawesome-free/js/all';
import './mascaras';
import './spinner';
import './autosize';
import './modal';
import './consents';
import './infoMarketing';
import './destroy_logs';